services:
  app:
    image: ${REGISTRY}/app:1.0
    deploy:
      mode: global
    ports:
      - 8080:8080
    environment:
      - NODE_HOSTNAME={{.Node.Hostname}}
    networks:
      - bully-net

networks:
  bully-net:
    driver: overlay
    attachable: true
