services:
  p1:
    build: .
    image: localhost:5000/app:1.0
    environment:
      NODE_ID: 1
      API_PORT: 8080
      NODO_1: p1
      NODO_2: p2
      NODO_3: p3
      NODO_4: p4
      NODO_5: p5
    networks:
      - bully-net
    restart: unless-stopped
    ports:
      - 8081:8080

  p2:
    build: .
    image: localhost:5000/app:1.0
    environment:
      NODE_ID: 2
      API_PORT: 8080
      NODO_1: p1
      NODO_2: p2
      NODO_3: p3
      NODO_4: p4
      NODO_5: p5
    networks:
      - bully-net
    restart: unless-stopped
    ports:
      - 8082:8080

  p3:
    build: .
    image: localhost:5000/app:1.0
    environment:
      NODE_ID: 3
      API_PORT: 8080
      NODO_1: p1
      NODO_2: p2
      NODO_3: p3
      NODO_4: p4
      NODO_5: p5
    networks:
      - bully-net
    restart: unless-stopped
    ports:
      - 8083:8080

  p4:
    build: .
    image: localhost:5000/app:1.0
    environment:
      NODE_ID: 4
      API_PORT: 8080
      NODO_1: p1
      NODO_2: p2
      NODO_3: p3
      NODO_4: p4
      NODO_5: p5
    networks:
      - bully-net
    restart: unless-stopped
    ports:
      - 8084:8080

  p5:
    build: .
    image: localhost:5000/app:1.0
    environment:
      NODE_ID: 5
      API_PORT: 8080
      NODO_1: p1
      NODO_2: p2
      NODO_3: p3
      NODO_4: p4
      NODO_5: p5
    networks:
      - bully-net
    restart: unless-stopped
    ports:
      - 8085:8080

networks:
  bully-net:
    driver: bridge
